name: Sync NPM Lockfile for AI-Refined Branches

on:
  push:
    branches:
      - 'ai_refined_code_*'
    paths:
      - 'package.json'

jobs:
  sync-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check for lockfile changes
        id: lockfile
        run: |
          if [ -f package-lock.json ] && ! git ls-files --error-unmatch package-lock.json >/dev/null 2>&1; then
            echo "Lockfile created."
            echo "changed=true" >> $GITHUB_OUTPUT
          elif ! git diff --quiet package-lock.json; then
            echo "Lockfile changed."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No lockfile changes."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push lockfile if changed
        if: steps.lockfile.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "chore: update package-lock.json after AI package.json change"
          git push

      # Optionally, run tests/build here
      # - name: Run tests
      #   run: npm test